<?php

namespace Warete\Cli\Tests\Command;

use PHPUnit\Framework\Attributes\AllowMockObjectsWithoutExpectations;
use PHPUnit\Framework\Attributes\TestWith;
use PHPUnit\Framework\TestCase;

#[AllowMockObjectsWithoutExpectations]
class BaseCommandTest extends TestCase
{
    public function testGetAutogeneratedName(): void
    {
        $command = new DummyCommand();

        $this->assertSame('dummy', $command->getName());
    }

    public function testGetDefaultDescription(): void
    {
        $command = new DummyCommand();

        $this->assertSame('', $command->getDescription());
    }

    #[TestWith(['dummy', true])]
    #[TestWith(['foo', false])]
    #[TestWith(['', false])]
    public function testSupports(
        string $name,
        bool $expected,
    ): void {
        $command = new DummyCommand();

        $this->assertEquals($expected, $command->supports($name));
    }
}
